INFO - 2023-04-25 02:25:52,512 - process: 7676 - scheduler.py - gerapy.server.core.scheduler - 105 - scheduler - successfully synced task with jobs with force
ERROR - 2023-04-25 02:25:59,312 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:25:59,852 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - HTTPConnectionPool(host='127.0.0.1', port=6800): Read timed out. (read timeout=3)
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1368, in getresponse
    response.begin()
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 317, in begin
    version, status, reason = self._read_status()
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 278, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=6800): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 120, in client_status
    requests.get(scrapyd_url(client.ip, client.port), timeout=3)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=6800): Read timed out. (read timeout=3)
INFO - 2023-04-25 02:26:14,587 - process: 7676 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_traffic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_traffic\project-1.0-py3.10.egg
ERROR - 2023-04-25 02:26:36,155 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:26:48,960 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:27:37,717 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:27:50,434 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 461, in project_deploy
    scrapyd.add_version(project_name, int(time.time()), egg_file.read())
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 76, in add_version
    json = self.client.post(url, data=data, files=files,
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:27:56,577 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 461, in project_deploy
    scrapyd.add_version(project_name, int(time.time()), egg_file.read())
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 76, in add_version
    json = self.client.post(url, data=data, files=files,
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
INFO - 2023-04-25 02:27:57,376 - process: 7676 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_ly to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_ly\project-1.0-py3.10.egg
ERROR - 2023-04-25 02:28:02,285 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 461, in project_deploy
    scrapyd.add_version(project_name, int(time.time()), egg_file.read())
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 76, in add_version
    json = self.client.post(url, data=data, files=files,
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:28:38,525 - process: 7676 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
