INFO - 2023-04-25 22:02:26,634 - process: 1596 - scheduler.py - gerapy.server.core.scheduler - 105 - scheduler - successfully synced task with jobs with force
ERROR - 2023-04-25 22:03:50,065 - process: 1596 - utils.py - gerapy.server.core.utils - 564 - utils - 'spider_scenic'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 690, in job_list
    result = scrapyd.list_jobs(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 139, in list_jobs
    jobs = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'spider_scenic'
INFO - 2023-04-25 22:04:11,862 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:06:56,698 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
ERROR - 2023-04-25 22:08:54,833 - process: 1596 - utils.py - gerapy.server.core.utils - 564 - utils - [WinError 3] 系统找不到指定的路径。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_scenic\\projects\\spider_scenic'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 452, in project_deploy
    egg = find_egg(project_path)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\build.py", line 89, in find_egg
    items = os.listdir(path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_scenic\\projects\\spider_scenic'
INFO - 2023-04-25 22:08:56,349 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
ERROR - 2023-04-25 22:08:57,673 - process: 1596 - utils.py - gerapy.server.core.utils - 564 - utils - [WinError 3] 系统找不到指定的路径。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_scenic\\projects\\spider_scenic'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 452, in project_deploy
    egg = find_egg(project_path)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\build.py", line 89, in find_egg
    items = os.listdir(path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_scenic\\projects\\spider_scenic'
INFO - 2023-04-25 22:08:58,856 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:11:15,588 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:12:05,887 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:13:10,593 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
ERROR - 2023-04-25 22:13:38,743 - process: 1596 - utils.py - gerapy.server.core.utils - 564 - utils - 'spider_scenic'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 690, in job_list
    result = scrapyd.list_jobs(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 139, in list_jobs
    jobs = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'spider_scenic'
ERROR - 2023-04-25 22:13:43,748 - process: 1596 - utils.py - gerapy.server.core.utils - 564 - utils - 'spider_scenic'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 690, in job_list
    result = scrapyd.list_jobs(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 139, in list_jobs
    jobs = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'spider_scenic'
INFO - 2023-04-25 22:15:03,576 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:17:44,590 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
INFO - 2023-04-25 22:18:08,118 - process: 1596 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_scenic to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_scenic\spider_scenic-1.0-py3.10.egg
