INFO - 2023-04-25 02:28:55,980 - process: 3048 - scheduler.py - gerapy.server.core.scheduler - 105 - scheduler - successfully synced task with jobs with force
ERROR - 2023-04-25 02:29:12,358 - process: 3048 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
INFO - 2023-04-25 02:29:24,074 - process: 3048 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_ly to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_ly\project-1.0-py3.10.egg
ERROR - 2023-04-25 02:29:28,612 - process: 3048 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 461, in project_deploy
    scrapyd.add_version(project_name, int(time.time()), egg_file.read())
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 76, in add_version
    json = self.client.post(url, data=data, files=files,
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:30:45,621 - process: 3048 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 189, in spider_list
    spiders = scrapyd.list_spiders(project_name)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 158, in list_spiders
    json = self.client.get(url, params=params, timeout=self.timeout)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
ERROR - 2023-04-25 02:31:27,307 - process: 3048 - utils.py - gerapy.server.core.utils - 564 - utils - [WinError 5] 拒绝访问。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_ly\\spider_ly\\log'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 653, in project_file_delete
    result = os.remove(path)
PermissionError: [WinError 5] 拒绝访问。: 'E:\\tuling\\tl\\travel\\gerapyDemo\\gerapy\\projects\\spider_ly\\spider_ly\\log'
INFO - 2023-04-25 02:31:44,885 - process: 3048 - build.py - gerapy.server.core.build - 24 - build - successfully build project spider_ly to egg file E:\tuling\tl\travel\gerapyDemo\gerapy\projects\spider_ly\project-1.0-py3.10.egg
ERROR - 2023-04-25 02:31:50,477 - process: 3048 - utils.py - gerapy.server.core.utils - 564 - utils - 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\utils.py", line 562, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\gerapy\server\core\views.py", line 461, in project_deploy
    scrapyd.add_version(project_name, int(time.time()), egg_file.read())
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\wrapper.py", line 76, in add_version
    json = self.client.post(url, data=data, files=files,
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 38, in request
    return self._handle_response(response)
  File "C:\Users\86166\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapyd_api\client.py", line 34, in _handle_response
    raise ScrapydResponseError(json['message'])
scrapyd_api.exceptions.ScrapydResponseError: 'str' object has no attribute 'decode'
